"""Build site/assets/data.js for the fair mitigation finance explorer from the
three CSVs in Data/explorer/ (indicator values, indicator-derived regional
shares with the AR6 TS.25 investment-need bounds, and 2019 population and GDP).

No third-party dependencies; run with any Python 3:
    python3 Code/build_explorer_data.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "Data" / "explorer"
OUT = ROOT / "site" / "assets" / "data.js"

REGIONS = [
    ("SAP", "South-East Asia and developing Pacific"),
    ("MEA", "Middle East"),
    ("APD", "Asia-Pacific Developed"),
    ("AFR", "Africa"),
    ("SAS", "Southern Asia"),
    ("LAC", "Latin America and Caribbean"),
    ("EEA", "Eastern Europe and West-Central Asia"),
    ("EAS", "Eastern Asia"),
    ("EUR", "Europe"),
    ("NAM", "North America"),
]

INDICATORS = [
    # key, short, principle, label, units (for raw values)
    ("1850 CO2FFI", "R1", "R", "1850–2019 CO₂-FFI", "GtCO₂ (1850–2019)"),
    ("1990 CO2FFI", "R2", "R", "1990–2019 CO₂-FFI", "GtCO₂ (1990–2019)"),
    ("GDP per Capita (2019)", "C1", "C", "GDP per capita (2019)", "USD PPP 2017 per capita"),
    ("Capital stock per Capita (2019)", "C2", "C", "Capital stock per capita (2019)", "USD PPP 2017 per capita"),
    ("DLS deprivation (2015)", "N1", "N", "DLS deprivation (2015)", "share deprived (avg. across dimensions)"),
    ("Climate risk (2030)", "N2", "N", "Climate risk (2030)", "share of population at acute risk"),
]


def read(name: str) -> dict[str, dict[str, float]]:
    with (DATA / name).open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    out = {}
    for row in rows:
        key = row.pop("regionshort")
        out[key] = {k: float(v) for k, v in row.items()}
    return out


def main() -> None:
    raw = read("equity_raw.csv")
    shares = read("equity_shares.csv")
    popgdp = read("popgdp_r10.csv")

    payload = {
        "regions": [{"code": c, "name": n} for c, n in REGIONS],
        "indicators": [
            {"key": k, "short": s, "principle": p, "label": l, "units": u}
            for k, s, p, l, u in INDICATORS
        ],
        "principles": [
            {"key": "R", "label": "Responsibility"},
            {"key": "C", "label": "Capability"},
            {"key": "N", "label": "Need"},
        ],
        "bounds": [
            {"key": "CE_low", "label": "Lower bound"},
            {"key": "CE_high", "label": "Upper bound"},
        ],
        "raw": raw,
        "shares": shares,
        "popgdp": popgdp,
    }
    OUT.write_text(
        "// Generated by scripts/build_data.py — do not edit by hand.\n"
        "window.FIE_DATA = " + json.dumps(payload, indent=1) + ";\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
